name: model_package
description: Model package.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  moor: ^3.3.1
  sqlite3_flutter_libs: ^0.2.0
  path_provider: ^1.6.14
  path: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^3.3.1
  build_runner: ^1.10.0

